"use strict";
const test=require("node:test"),assert=require("node:assert/strict"),fs=require("node:fs"),vm=require("node:vm"),path=require("node:path");
const {createDocument}=require("./helpers/trottl-special-dom.cjs");
const read=f=>fs.readFileSync(path.join(__dirname,"..",f),"utf8").replace(/\r/g,"");
const migration=read("supabase/migrations/20260915030000_add_trottl_special_reaction_test.sql");
const flush=async()=>{for(let i=0;i<8;i++)await new Promise(r=>setImmediate(r));};
const intro=100000,start=intro+5000;
function rank(rows){const valid=rows.filter(x=>x.status==="completed"),values=valid.map(x=>x.reaction_ms),best=Math.min(...values),worst=Math.max(...values),different=best!==worst;return rows.map(x=>({...x,winner:x.status==="completed"&&x.reaction_ms===best,loser:x.status!=="completed"||(different&&x.status==="completed"&&x.reaction_ms===worst)})).sort((a,b)=>(a.status!=="completed")-(b.status!=="completed")||(a.reaction_ms??0)-(b.reaction_ms??0)||a.seat-b.seat);}

function harness({role="player",delay=2000,status="open",reaction=null,now=intro,user="u0"}={}){
 const doc=createDocument('<body><div id="root"></div></body>'),root=doc.querySelector("#root"),timers=new Set(),calls=[],decoded=[];
 function Image(){this.decode=()=>{decoded.push(this.src);return Promise.resolve();};}
 const win={document:doc,Image,performance:{now:()=>now},setInterval:f=>{timers.add(f);return f;},clearInterval:f=>timers.delete(f)};
 for(const f of ["trottl-special-minigames.js","trottl-special-reaction-test.js"])vm.runInNewContext(read(f),{window:win,Date,Number,Math,Object,Array,Set,Map,JSON,Promise});
 const runs={u0:{status,reaction_ms:reaction,completed:status!=="open"},u1:{status:"open",reaction_ms:null,completed:false}};
 const reactionRun={player_id:role==="spectator"?"u0":user,delay_ms:delay,signal_at:new Date(start+delay).toISOString(),status,reaction_ms:reaction};
 const snapshot={membershipRole:role,identity:{userId:user},players:[{userId:"u0",lifecycle:"alive"},{userId:"u1",lifecycle:"critical"}],reactionRun,session:{id:"s1",status:"playing",hostUserId:"u0",gameState:{phase:"minigame_active",minigame:{minigame_id:"r1",minigame_type:"special_minigame_03",title:"Reaktionstest",title_started_at:new Date(intro).toISOString(),title_ends_at:new Date(intro+2000).toISOString(),start_at:new Date(start).toISOString(),end_at:new Date(start+10000).toISOString(),participants:[{player_id:"u0"},{player_id:"u1"}],runs}}}};
 const service={serverNow:()=>now,submitReaction:async(id,round,elapsed)=>{calls.push({type:"tap",id,round,elapsed});const outcome=elapsed<delay?"false_start":"completed";Object.assign(reactionRun,{status:outcome,reaction_ms:outcome==="completed"?elapsed-delay:null});Object.assign(runs[user],{status:outcome,reaction_ms:reactionRun.reaction_ms,completed:true});return snapshot;},finalizeReaction:async(id,round)=>{calls.push({type:"finalize",id,round});Object.assign(reactionRun,{status:"timeout",reaction_ms:null});Object.assign(runs[user]??runs.u0,{status:"timeout",reaction_ms:null,completed:true});return snapshot;}};
 let c=win.TrottlSpecialReactionTest.create({root,service,onSnapshot:s=>c.update(s),onError(){}});c.update(snapshot);
 const clock=t=>{now=t;for(const f of [...timers])f();};
 const tap=()=>{const field=root.querySelector(".trottl-special-reaction-field");for(const f of field.listeners.pointerdown??[])f({isTrusted:true,pointerType:"touch",button:0,preventDefault(){}});};
 return{win,doc,root,snapshot,reactionRun,calls,decoded,clock,tap,recreate:()=>{c.suspend();c=win.TrottlSpecialReactionTest.create({root,service,onSnapshot:s=>c.update(s),onError(){}});c.update(snapshot);return c;}};
}

test("registry exposes exactly the first eight stable productive minigames",()=>{const h=harness();assert.equal(h.win.TrottlSpecialMinigames.registry.length,10);assert.deepEqual(Array.from(h.win.TrottlSpecialMinigames.registry.filter(x=>x.active),x=>[x.id,x.title]),[["special_minigame_01","Zahlenjagd"],["special_minigame_02","Fischfang"],["special_minigame_03","Reaktionstest"],["special_minigame_04","Farbenchaos"],["special_minigame_05","Fisch-Memory"],["special_minigame_06","Stop den Fisch"],["special_minigame_07","Giftfisch"],["special_minigame_08","Fische zählen"]]);});
test("salmon asset is preloaded and decoded by the controller, not by the global HTML start path",async()=>{const h=harness();await flush();assert.equal(h.win.TrottlSpecialReactionTest.SALMON_ASSET,"./assets/mini-games/lachs-fish.webp");assert.deepEqual(h.decoded,["./assets/mini-games/lachs-fish.webp"]);assert.equal(h.root.querySelector(".trottl-special-reaction-salmon").src,"./assets/mini-games/lachs-fish.webp");assert.doesNotMatch(read("index.html"),/<link rel="preload"[^>]+assets\/mini-games/i);});
test("shared title/countdown/START becomes WARTE before the private signal",()=>{const h=harness();for(const [t,text] of [[intro,"Reaktionstest"],[intro+2000,"3"],[intro+3000,"2"],[intro+4000,"1"],[start,"START!"]])assert.equal(h.win.TrottlSpecialMinigames.sequence(h.snapshot.session.gameState.minigame,t).label,text);h.clock(start+100);assert.equal(h.root.querySelector(".trottl-special-reaction-label").textContent,"WARTE...");assert.equal(h.root.querySelector(".trottl-special-reaction-salmon").hidden,true);});
test("at the exact stored signal TIPPEN and salmon appear without a transition",()=>{const h=harness({delay:3840});h.clock(start+3839);assert.equal(h.root.querySelector(".trottl-special-reaction-salmon").hidden,true);h.clock(start+3840);assert.equal(h.root.querySelector(".trottl-special-reaction-label").textContent,"TIPPEN!");assert.equal(h.root.querySelector(".trottl-special-reaction-salmon").hidden,false);const rule=read("trottl-special.css").match(/\.trottl-special-reaction-salmon \{([^}]*)\}/)[1];assert.doesNotMatch(rule,/transition|animation|opacity/);});
test("first valid pointerdown freezes millisecond reaction, hides fish and ignores repeats",async()=>{const h=harness({delay:2500});h.clock(start+2747);h.tap();h.tap();assert.equal(h.root.querySelector(".trottl-special-reaction-salmon").hidden,true);assert.equal(h.root.querySelector(".trottl-special-reaction-result").textContent,"247 ms");await flush();assert.deepEqual(h.calls,[{type:"tap",id:"s1",round:"r1",elapsed:2747}]);});
test("one millisecond early and clearly early taps become explicit false starts",async()=>{for(const elapsed of [1999,400]){const h=harness({delay:2000});h.clock(start+elapsed);h.tap();assert.equal(h.root.querySelector(".trottl-special-reaction-result").textContent,"FEHLSTART");assert.equal(h.root.querySelector(".trottl-special-reaction-result").classList.contains("is-penalty"),true);await flush();assert.equal(h.reactionRun.status,"false_start");assert.equal(h.reactionRun.reaction_ms,null);}});
test("hard ten-second deadline renders timeout and asks server to finalize once in flight",async()=>{const h=harness({delay:8500});h.clock(start+9999);assert.equal(h.root.querySelector(".trottl-special-reaction-salmon").hidden,false);h.clock(start+10000);assert.equal(h.root.querySelector(".trottl-special-reaction-result").textContent,"ZEIT ABGELAUFEN");await flush();assert.equal(h.calls[0].type,"finalize");h.tap();assert.equal(h.calls.filter(x=>x.type==="tap").length,0);});
test("reconnect preserves stored pre-signal and post-signal absolute timing",()=>{const h=harness({delay:7110});h.clock(start+5000);h.recreate();assert.equal(h.root.querySelectorAll(".trottl-special-reaction-label").at(-1).textContent,"WARTE...");h.clock(start+7200);h.recreate();assert.equal(h.root.querySelectorAll(".trottl-special-reaction-label").at(-1).textContent,"TIPPEN!");assert.equal(h.reactionRun.signal_at,new Date(start+7110).toISOString());});
test("completed, false-start and timeout reconnect states stay noninteractive",()=>{for(const [status,reaction,label] of [["completed",218,"218 ms"],["false_start",null,"FEHLSTART"],["timeout",null,"ZEIT ABGELAUFEN"]]){const h=harness({status,reaction,now:start+9000});assert.equal(h.root.querySelector(".trottl-special-reaction-result").textContent,label);h.tap();assert.equal(h.calls.length,0);}});
test("spectator mirrors host signal and result but cannot interact",()=>{const h=harness({role:"spectator",user:"watcher",delay:2570});h.clock(start+2600);assert.equal(h.root.querySelector(".trottl-special-reaction-salmon").hidden,false);assert.match(h.root.querySelector(".trottl-special-minigame-copy").textContent,/Host-Sicht/);h.tap();assert.equal(h.calls.length,0);});
test("CSS keeps centered responsive salmon and explicit penalty styling",()=>{const css=read("trottl-special.css");assert.match(css,/reaction-salmon[^}]*width: clamp\(150px, 50%, 220px\)/);assert.match(css,/reaction-salmon[^}]*object-fit: contain/);assert.match(css,/reaction-result\.is-penalty/);assert.match(css,/prefers-reduced-motion: reduce/);});
test("server stores private independent 2.0–8.5s runs without public future signal or early result fields",()=>{for(const r of [/create table public\.trottl_special_reaction_runs/,/delay_ms integer not null check \(delay_ms between 2000 and 8500\)/,/2000\+floor\(pg_catalog\.random\(\)\*6501\)/,/signal_at timestamptz not null/,/revoke all on public\.trottl_special_reaction_runs from anon,authenticated/,/get_trottl_special_reaction_view/,/target:=auth\.uid\(\)/,/target:=s\.host_user_id/,/public_run=jsonb_build_object\('status',outcome,'completed',true\)/])assert.match(migration,r);assert.doesNotMatch(migration,/runs:=runs\|\|jsonb_build_object\([^\n]*delay_ms|public_run=jsonb_build_object\([^\n]*reaction_ms/);});
test("server tap guard derives false-start/completed/timeout from stored delay and deadline",()=>{for(const r of [/p_tap_elapsed_ms<r\.delay_ms then outcome:='false_start'/,/else outcome:='completed';reaction:=p_tap_elapsed_ms-r\.delay_ms/,/now_at>=\(m->>'end_at'\)::timestamptz/,/p_tap_elapsed_ms>server_elapsed\+1000/,/status in \('open','completed','false_start','timeout'\)/])assert.match(migration,r);});
test("custom ranking puts penalties last and implements winner/loser edge rules",()=>{for(const r of [/order by \(status<>'completed'\),reaction_ms nulls last,seat_order/,/'is_winner',status='completed' and reaction_ms=best/,/'is_loser',status<>'completed' or \(best is distinct from worst/,/all_tied:=penalty_count=0 and valid_count>0 and best=worst/,/'automatic_drinks',automatic,'distributions',distributions/])assert.match(migration,r);});
test("ranking matrix covers normal, one-valid, tied and mixed-penalty outcomes",()=>{const cases=[
 {rows:[["completed",200],["completed",300],["completed",400]],w:[0],l:[2]},
 {rows:[["completed",200],["completed",300],["false_start",null]],w:[0],l:[1,2]},
 {rows:[["completed",200],["timeout",null],["false_start",null]],w:[0],l:[1,2]},
 {rows:[["completed",200],["completed",200],["false_start",null]],w:[0,1],l:[2]},
 {rows:[["completed",200],["completed",200],["completed",200]],w:[0,1,2],l:[]},
 {rows:[["false_start",null],["timeout",null],["timeout",null]],w:[],l:[0,1,2]},
 ];for(const c of cases){const out=rank(c.rows.map(([status,reaction_ms],seat)=>({status,reaction_ms,seat})));assert.deepEqual(out.filter(x=>x.winner).map(x=>x.seat).sort(),c.w);assert.deepEqual(out.filter(x=>x.loser).map(x=>x.seat).sort(),c.l);const firstPenalty=out.findIndex(x=>x.status!=="completed");if(firstPenalty>=0)assert.ok(out.slice(firstPenalty).every(x=>x.status!=="completed"));}});
test("productive pool and debug override route exactly IDs 01–03",()=>{assert.match(migration,/where id='special_minigame_03'/);for(const id of ["01","02","03"])assert.match(migration,new RegExp(`chosen='special_minigame_${id}'`));assert.doesNotMatch(migration,/chosen='special_minigame_0[4-9]'|chosen='special_minigame_10'/);assert.match(read("trottl-special-debug.js"),/registry\.filter\(r => r\.active && r\.implemented\)/);});
test("controlled pool boundaries map uniformly to the five implemented IDs",()=>{const pick=n=>`special_minigame_0${1+Math.floor(n*5)}`;for(const [n,id] of [[0,"01"],[.199999,"01"],[.2,"02"],[.399999,"02"],[.4,"03"],[.599999,"03"],[.6,"04"],[.799999,"04"],[.8,"05"],[.999999,"05"]])assert.equal(pick(n),`special_minigame_${id}`);const fixture=read("tests/fixtures/trottl-special-color-chaos.sql");for(const sample of ["0.199999","0.2","0.4","0.6","0.8"])assert.ok(fixture.includes(sample));});
test("service exposes one completion RPC and one deadline RPC using the shared server clock",()=>{const service=read("trottl-special-service.js");assert.match(service,/submitReaction: async/);assert.match(service,/finalizeReaction: async/);assert.match(service,/clockAnchor \+ monotonicNow\(\) - clockLocal/);assert.match(service,/game_?state\?\.minigame\?\.minigame_type === "special_minigame_03"/);});
test("existing result panel renders null penalty ranks and explicit red rows",()=>{const ui=read("trottl-special-ui.js");assert.match(ui,/row\.rank == null \? ""/);assert.match(ui,/row\.is_penalty \? " is-penalty"/);assert.match(ui,/Ergebnisse von „\$\{m\.title \?\? m\.minigame_type\}“ Game/);});
test("cache wiring retains existing games while shared Special assets advance",()=>{const html=read("index.html");assert.match(html,/trottl-special-reaction-test\.js\?v=2/);assert.match(html,/trottl-special-color-chaos\.js\?v=3/);assert.match(html,/trottl-special\.css\?v=31/);assert.match(html,/trottl-special-service\.js\?v=19/);assert.match(html,/trottl-special-minigames\.js\?v=8/);assert.match(html,/trottl-special-ui\.js\?v=23/);});
test("dedicated PostgreSQL fixture covers private delays and real drink settlement",()=>{const fixture=read("tests/fixtures/trottl-special-reaction-test.sql");assert.match(fixture,/Private delay state/);assert.match(fixture,/Reaction ranking\/settlement/);assert.match(fixture,/automatic_drinks/);assert.ok(fixture.trim().endsWith("rollback;"));});
test("migration is additive, transactional, private and leaves Classic, life and finale untouched",()=>{assert.ok(migration.startsWith("begin;\n"));assert.ok(migration.endsWith("commit;\n"));assert.equal((migration.match(/\$\$/g)??[]).length%2,0);assert.doesNotMatch(migration,/trottl_classic|special_apply_life|finale/);for(const fn of [/special_reaction_begin_locked/,/special_reaction_finalize_locked/,/get_trottl_special_reaction_view/,/submit_trottl_special_reaction/,/finalize_trottl_special_reaction/])assert.match(migration,fn);});
