"use strict";
const test=require("node:test"),assert=require("node:assert/strict"),fs=require("node:fs"),vm=require("node:vm"),path=require("node:path");
const {createDocument}=require("./helpers/trottl-special-dom.cjs");
const read=file=>fs.readFileSync(path.join(__dirname,"..",file),"utf8").replace(/\r/g,"");
const source=read("trottl-special-fish-memory.js"),migration=read("supabase/migrations/20260918010000_add_trottl_special_fish_memory.sql");
const flush=async()=>{for(let i=0;i<16;i++)await new Promise(resolve=>setImmediate(resolve));};
const intro=200000,start=intro+5000;

function harness({role="player",phase="watch",memoryRound=1,guessCount=0,completed=false,errors=null,now=start+400,pattern=null}={}){
 const doc=createDocument('<body><div id="root"></div></body>'),root=doc.querySelector("#root"),calls=[],images=[],intervals=new Set();
 function Image(){images.push(this);this.decode=()=>Promise.resolve();}
 const win={document:doc,Image,setTimeout,clearTimeout,setInterval:fn=>{intervals.add(fn);return fn;},clearInterval:fn=>intervals.delete(fn)};
 vm.runInNewContext(read("trottl-special-minigames.js"),{window:win,Date,Number,Math,Object,Array,Set,Map,JSON,Promise,BigInt});
 vm.runInNewContext(source,{window:win,Date,Number,Math,Object,Array,Set,Map,JSON,Promise,BigInt});
 const sequence=pattern??[...win.TrottlSpecialFishMemory.generatePattern(92831)],guesses=[];
 for(let i=0;i<guessCount;i++)guesses.push(sequence[i]);
 const watchMs=memoryRound*4*1020,phaseStart=phase==="watch"?start+400:start+400+watchMs;
 const view={player_id:"u0",pattern:sequence,memory_round:memoryRound,phase,phase_started_at:new Date(phaseStart).toISOString(),
  phase_ends_at:phase==="watch"?new Date(phaseStart+watchMs).toISOString():null,
  input_deadline:phase==="input"?new Date(phaseStart+[8000,13000,18000][memoryRound-1]).toISOString():null,
  guess_count:guessCount,completed,errors};
 const runs={u0:{memory_round:memoryRound,phase,guess_count:guessCount,completed},u1:{memory_round:1,phase:"watch",guess_count:0,completed:false}};
 const snapshot={membershipRole:role,identity:{userId:role==="spectator"?"watcher":"u0"},players:[{userId:"u0",lifecycle:"alive"},{userId:"u1",lifecycle:"critical"}],fishMemoryView:view,
  session:{id:"s1",status:"playing",hostUserId:"u0",gameState:{phase:"minigame_active",minigame:{minigame_id:"r5",minigame_type:"special_minigame_05",title:"Fisch-Memory",
   title_started_at:new Date(intro).toISOString(),title_ends_at:new Date(intro+2000).toISOString(),start_at:new Date(start).toISOString(),ranking_direction:"lower_is_better",
   participants:[{player_id:"u0"},{player_id:"u1"}],runs}}}};
 let totalErrors=errors??0;
 function transitionAfterRound(){
  totalErrors+=win.TrottlSpecialFishMemory.countErrors(sequence,guesses,memoryRound*4);guesses.length=0;
  if(memoryRound<3){memoryRound+=1;view.memory_round=memoryRound;view.phase="watch";view.phase_started_at=new Date(now).toISOString();view.phase_ends_at=new Date(now+memoryRound*4*1020).toISOString();view.input_deadline=null;view.guess_count=0;Object.assign(runs.u0,{memory_round:memoryRound,phase:"watch",guess_count:0});}
  else{view.phase="finished";view.completed=true;view.errors=totalErrors;view.phase_started_at=new Date(now).toISOString();view.phase_ends_at=null;view.input_deadline=null;Object.assign(runs.u0,{phase:"finished",completed:true});}
 }
 const service={serverNow:()=>now,guessFishMemory:async(id,round,memoryRoundArg,guessIndex,color,clientTimestamp)=>{
  calls.push({type:"guess",id,round,memoryRound:memoryRoundArg,guessIndex,color,clientTimestamp});
  if(view.phase!=="input"||memoryRoundArg!==view.memory_round||guessIndex!==view.guess_count)throw Error("SPECIAL_STALE_FISH_MEMORY_GUESS");
  guesses.push(color);view.guess_count+=1;runs.u0.guess_count=view.guess_count;if(view.guess_count===view.memory_round*4)transitionAfterRound();return snapshot;
 },syncFishMemory:async(id,round)=>{calls.push({type:"sync",id,round});if(view.phase==="watch"){view.phase="input";view.phase_started_at=view.phase_ends_at;view.phase_ends_at=null;view.input_deadline=new Date(now+[8000,13000,18000][view.memory_round-1]).toISOString();runs.u0.phase="input";}else if(view.phase==="input")transitionAfterRound();return snapshot;}};
 let controller=win.TrottlSpecialFishMemory.create({root,service,onSnapshot:next=>controller.update(next),onError(){}});controller.update(snapshot);
 const clock=value=>{now=value;for(const fn of [...intervals])fn();};
 const tap=color=>{const button=root.querySelectorAll(".trottl-special-fish-memory-choice").find(item=>item.dataset.color===color);for(const fn of button.listeners.pointerdown??[])fn({isTrusted:true,pointerType:"touch",button:0,preventDefault(){}});};
 return{win,doc,root,view,snapshot,calls,images,clock,tap,get now(){return now;},recreate(){controller.suspend();controller=win.TrottlSpecialFishMemory.create({root,service,onSnapshot:next=>controller.update(next),onError(){}});controller.update(snapshot);return controller;}};
}

test("global deterministic generator returns exactly twelve valid colors and never three equal in a row",()=>{const h=harness(),api=h.win.TrottlSpecialFishMemory;
 for(let seed=1;seed<=200;seed++){const pattern=[...api.generatePattern(seed)];assert.equal(pattern.length,12);assert.ok(pattern.every(color=>api.COLORS.includes(color)));for(let i=2;i<12;i++)assert.ok(!(pattern[i]===pattern[i-1]&&pattern[i]===pattern[i-2]));assert.deepEqual(pattern,[...api.generatePattern(seed)]);}
 assert.ok(Array.from({length:500},(_,i)=>api.generatePattern(i+1)).some(pattern=>pattern.some((color,i)=>i>0&&color===pattern[i-1])));
});
test("cumulative round lengths are 4, 8 and 12 and reuse the same pattern prefix",()=>{const h=harness(),api=h.win.TrottlSpecialFishMemory,p=[...api.generatePattern(77)];assert.deepEqual([1,2,3].map(api.targetCount),[4,8,12]);assert.deepEqual(p.slice(0,4),p.slice(0,8).slice(0,4));assert.deepEqual(p.slice(0,8),p.slice(0,12).slice(0,8));});
test("flash timing is 800ms active plus 220ms neutral and repeated fish flash twice",()=>{const h=harness(),api=h.win.TrottlSpecialFishMemory,p=["BLUE","BLUE","RED","GREEN","YELLOW","RED","BLUE","GREEN","RED","YELLOW","BLUE","GREEN"];
 assert.deepEqual(JSON.parse(JSON.stringify(api.flashFrame(p,1,0))),{index:0,color:"BLUE",active:true});assert.equal(api.flashFrame(p,1,799).active,true);assert.equal(api.flashFrame(p,1,800).active,false);assert.equal(api.flashFrame(p,1,1019).active,false);assert.deepEqual(JSON.parse(JSON.stringify(api.flashFrame(p,1,1020))),{index:1,color:"BLUE",active:true});});
test("shared WATCH cadence reserves every 800ms flash and 220ms separation",()=>{const api=harness().win.TrottlSpecialFishMemory,p=["RED","BLUE","BLUE","GREEN","YELLOW","RED","BLUE","GREEN","RED","YELLOW","BLUE","GREEN"];assert.deepEqual([1,2,3].map(api.watchDurationMs),[4080,8160,12240]);for(const round of [1,2,3]){const end=api.watchDurationMs(round);assert.equal(api.flashFrame(p,round,end-221).active,true);assert.equal(api.flashFrame(p,round,end-220).active,false);assert.equal(api.flashFrame(p,round,end).index,round*4);}});
test("position-wise scoring counts wrong and missing guesses without time ranking",()=>{const h=harness(),count=h.win.TrottlSpecialFishMemory.countErrors;assert.equal(count(["RED","BLUE","GREEN","YELLOW"],["RED","YELLOW","GREEN","RED"],4),2);assert.equal(count(["RED","BLUE","GREEN","YELLOW"],["RED","BLUE"],4),2);});
test("round 1 timeout scores two submitted guesses plus two missing positions",()=>{const count=harness().win.TrottlSpecialFishMemory.countErrors,expected=["RED","BLUE","GREEN","YELLOW"];assert.equal(count(expected,["RED","YELLOW"],4),3);});
test("round 2 timeout scores five submitted guesses plus three missing positions",()=>{const count=harness().win.TrottlSpecialFishMemory.countErrors,expected=["RED","BLUE","GREEN","YELLOW","RED","BLUE","GREEN","YELLOW"];assert.equal(count(expected,expected.slice(0,5),8),3);});
test("round 3 timeout scores nine submitted guesses plus three missing positions and accumulated rounds sum to six",()=>{const count=harness().win.TrottlSpecialFishMemory.countErrors,expected=["RED","BLUE","GREEN","YELLOW","RED","BLUE","GREEN","YELLOW","RED","BLUE","GREEN","YELLOW"];assert.equal(count(expected,expected.slice(0,9),12),3);assert.equal(1+3+2,6);});
test("all four fish PNGs preload and decode before play",async()=>{const h=harness();await flush();assert.deepEqual(h.images.map(image=>image.src),["./assets/mini-games/red-fish.png","./assets/mini-games/blue-fish.png","./assets/mini-games/green-fish.png","./assets/mini-games/yellow-fish.png"]);});
test("countdown and START preview the calm board while the title remains hidden",()=>{const h=harness({now:intro});h.clock(intro);assert.equal(h.root.querySelector(".trottl-special-minigame-content").hidden,true);for(const moment of [intro+2000,intro+3000,intro+4000,start,start+399]){h.clock(moment);assert.equal(h.root.querySelector(".trottl-special-minigame-content").hidden,false);assert.equal(h.root.querySelector(".trottl-special-fish-memory-game").hidden,false);assert.equal(h.root.querySelector(".trottl-special-fish-memory-instruction").textContent,"MERKE DIR DIE REIHENFOLGE!");assert.equal(h.root.querySelectorAll(".trottl-special-fish-memory-choice.is-sequence-active").length,0);assert.equal(h.root.querySelectorAll(".trottl-special-fish-memory-choice").every(button=>button.disabled),true);assert.equal(h.root.querySelectorAll(".trottl-special-fish-memory-dot").length,0);}h.clock(start+400);assert.equal(h.root.querySelector(".trottl-special-fish-memory-game").hidden,false);});
test("fixed 2x2 fields retain RED BLUE GREEN YELLOW order",()=>{const h=harness();assert.deepEqual(h.root.querySelectorAll(".trottl-special-fish-memory-choice").map(button=>button.dataset.color),["RED","BLUE","GREEN","YELLOW"]);assert.equal(h.root.querySelectorAll(".trottl-special-fish-memory-choice").length,4);});
test("WATCH shows attention state, one white flash and blocks every input",()=>{const p=["RED","BLUE","GREEN","YELLOW","RED","BLUE","GREEN","YELLOW","RED","BLUE","GREEN","YELLOW"],h=harness({pattern:p,now:start+400});assert.ok(h.root.querySelector(".trottl-special-fish-memory-game").classList.contains("is-watch"));assert.equal(h.root.querySelector(".trottl-special-fish-memory-instruction").textContent,"MERKE DIR DIE REIHENFOLGE!");assert.deepEqual(h.root.querySelectorAll(".trottl-special-fish-memory-choice").filter(button=>button.classList.contains("is-sequence-active")).map(button=>button.dataset.color),["RED"]);h.tap("RED");assert.equal(h.calls.length,0);assert.ok(h.root.querySelectorAll(".trottl-special-fish-memory-choice").every(button=>button.disabled));});
test("INPUT uses neutral centered dots and never exposes correctness",async()=>{const h=harness({phase:"input",now:start+5000});h.tap("YELLOW");await flush();const dots=h.root.querySelectorAll(".trottl-special-fish-memory-dot");assert.equal(dots.length,4);assert.equal(dots.filter(dot=>dot.classList.contains("is-filled")).length,1);assert.doesNotMatch(h.root.textContent,/FALSCH|Fehler/i);assert.ok(h.root.querySelector(".trottl-special-fish-memory-game").classList.contains("is-input"));assert.ok(h.root.querySelectorAll(".trottl-special-fish-memory-choice").every(button=>!button.classList.contains("is-wrong")&&!button.classList.contains("is-correct")));});
test("rapid pointerdowns preserve exact local queue order and fill one dot per guess",async()=>{const h=harness({phase:"input",now:start+2500});for(const color of ["RED","BLUE","GREEN","YELLOW"])h.tap(color);await flush();assert.deepEqual(h.calls.filter(call=>call.type==="guess").map(call=>[call.guessIndex,call.color]),[[0,"RED"],[1,"BLUE"],[2,"GREEN"],[3,"YELLOW"]]);assert.equal(h.view.memory_round,2);assert.equal(h.view.phase,"watch");});
test("reconnect restores server round, phase, filled count and absolute deadline",()=>{const h=harness({phase:"input",memoryRound:2,guessCount:5,now:start+5000}),deadline=h.view.input_deadline;h.recreate();const game=h.root.querySelectorAll(".trottl-special-fish-memory-game").at(-1);assert.equal(game.querySelector(".trottl-special-fish-memory-round").textContent,"Runde 2 / 3");assert.equal(game.querySelectorAll(".trottl-special-fish-memory-dot").filter(dot=>dot.classList.contains("is-filled")).length,5);assert.equal(h.view.input_deadline,deadline);});
test("spectator renders host watch and input state but can never submit",()=>{const watch=harness({role:"spectator"});assert.equal(watch.root.querySelector(".trottl-special-fish-memory-instruction").textContent,"MERKE DIR DIE REIHENFOLGE!");watch.tap("RED");assert.equal(watch.calls.length,0);const input=harness({role:"spectator",phase:"input",guessCount:2,now:start+2500});assert.equal(input.root.querySelectorAll(".trottl-special-fish-memory-dot").filter(dot=>dot.classList.contains("is-filled")).length,2);input.tap("BLUE");assert.equal(input.calls.length,0);});
test("completed player sees own errors while spectator sees only host finish",()=>{const player=harness({completed:true,phase:"finished",memoryRound:3,errors:4});assert.equal(player.root.querySelector(".trottl-special-fish-memory-result").textContent,"FERTIG4 Fehler");const spectator=harness({role:"spectator",completed:true,phase:"finished",memoryRound:3,errors:null});assert.equal(spectator.root.querySelector(".trottl-special-fish-memory-result").textContent,"FERTIG");});
test("central tuning fixes input timers at 8s, 13s, 18s and flash cadence at 800/220",()=>{const c=harness().win.TrottlSpecialFishMemory.CONFIG;assert.deepEqual([...c.inputTimeoutMs],[8000,13000,18000]);assert.equal(c.activeFlashMs,800);assert.equal(c.flashPauseMs,220);});
test("server stores one shared pattern and separate private player runs",()=>{for(const regex of [/create table public\.trottl_special_fish_memory_rounds/,/pattern jsonb not null/,/create table public\.trottl_special_fish_memory_runs/,/foreign key \(session_id,round_id\)/,/seed_value:=1\+floor\(pg_catalog\.random\(\)\*2147483646\)/,/pattern_value:=public\.special_fish_memory_pattern\(seed_value\)/,/for p in select value from jsonb_array_elements\(g->'minigame'->'participants'\)/,/revoke all on public\.trottl_special_fish_memory_rounds,public\.trottl_special_fish_memory_runs from anon,authenticated/])assert.match(migration,regex);});
test("server generator permits doubles but redirects a third equal color",()=>{assert.match(migration,/value:=mod\(value::numeric\*48271,2147483647\)::bigint/);assert.match(migration,/if i>=3 and answer\[i-1\]=answer\[i-2\] and colors\[color_index\]=answer\[i-1\]/);assert.match(migration,/color_index:=1\+mod\(\(color_index-1\)\+1\+mod\(value\/4,3\)::integer,4\)/);});
test("server owns cumulative scoring, zero-based integer JSONB indexing, missing guesses and all three timeouts",()=>{for(const regex of [/p_memory_round\*4\*1020/,/when 1 then 8000 when 2 then 13000 when 3 then 18000/,/p_expected_count-count\(\*\)::integer\+count\(\*\) filter/,/p_pattern->>\(\(guess\.ordinality-1\)::integer\)/,/expected_count:=r\.memory_round\*4/,/accumulated_errors=r\.accumulated_errors\+round_errors/,/phase='finished'/])assert.match(migration,regex);assert.doesNotMatch(migration,/p_pattern->>\(guess\.ordinality-1\)/);});
test("initial WATCH begins after START while later personal rounds begin immediately",()=>{assert.match(migration,/start_at\+400\*interval '1 millisecond',start_at\+4480\*interval '1 millisecond'/);assert.match(migration,/phase_started_at=now_at,\n\s*phase_ends_at=now_at\+watch_ms\*interval '1 millisecond'/);});
test("guess RPC serializes index and color without returning correctness",()=>{const body=migration.match(/create function public\.guess_trottl_special_fish_memory[\s\S]*?\nend; \$\$/)?.[0]??"";assert.match(body,/p_guess_index is distinct from jsonb_array_length\(r\.guesses\)/);assert.match(body,/p_selected_color not in \('RED','BLUE','GREEN','YELLOW'\)/);assert.match(body,/return p_session_id/);assert.doesNotMatch(body,/return jsonb_build_object|correct|incorrect/);});
test("view selects self or spectator host and keeps pre-result spectator errors private",()=>{assert.match(migration,/then target:=auth\.uid\(\)/);assert.match(migration,/then target:=s\.host_user_id;is_spectator:=true/);assert.match(migration,/'errors',case when r\.completed and not is_spectator then r\.accumulated_errors else null end/);});
test("result ranking is lower-is-better and reuses shared tie and drink settlement",()=>{assert.match(migration,/special_minigame_begin_locked\(p_id,'special_minigame_05','lower_is_better'\)/);assert.match(migration,/special_minigame_finalize_locked\(p_id,\(m->>'minigame_id'\)::uuid,inputs\)/);const shared=read("supabase/migrations/20260913070000_add_trottl_special_number_hunt.sql");assert.match(shared,/all_tied',true/);assert.match(shared,/'automatic_drinks'/);assert.match(shared,/'distributions'/);});
test("productive pool and test selector expose exactly IDs 01 through 06",()=>{const h=harness(),active=Array.from(h.win.TrottlSpecialMinigames.registry.filter(item=>item.active),item=>item.id);assert.deepEqual(active,["special_minigame_01","special_minigame_02","special_minigame_03","special_minigame_04","special_minigame_05","special_minigame_06"]);assert.ok(h.win.TrottlSpecialMinigames.registry.slice(6).every(item=>!item.active&&!item.implemented));assert.match(read("trottl-special-debug.js"),/registry\.filter\(r => r\.active && r\.implemented\)/);});
test("five-game random boundaries are exactly twenty percent each",()=>{const pick=value=>1+Math.floor(value*5);for(const [value,id] of [[0,1],[.199999,1],[.2,2],[.399999,2],[.4,3],[.599999,3],[.6,4],[.799999,4],[.8,5],[.999999,5]])assert.equal(pick(value),id);});
test("mobile CSS keeps a stable larger card, fixed 2x2 grid, centered dynamic dots and reduced motion",()=>{const css=read("trottl-special.css");assert.match(css,/fish-memory-game[^}]*height: clamp\(370px, 52dvh, 470px\)/);assert.match(css,/minigame-shell\.is-fish-memory\.is-countdown .trottl-special-minigame-countdown[^}]*position: absolute/);assert.match(css,/fish-memory-grid[^}]*grid-template-columns: repeat\(2[^}]*grid-template-rows: repeat\(2/);assert.match(css,/fish-memory-dots[^}]*display: flex[^}]*justify-content: center/);assert.match(css,/fish-memory-game\.is-watch::before[^}]*animation:/);assert.match(css,/prefers-reduced-motion: reduce[^}]*fish-memory-game\.is-watch::before[^}]*animation: none/);});
test("controller, service and cache wiring are versioned without bumping existing game controllers",()=>{const html=read("index.html"),service=read("trottl-special-service.js"),ui=read("trottl-special-ui.js");assert.match(html,/trottl-special-fish-memory\.js\?v=3/);assert.match(html,/trottl-special-minigames\.js\?v=6/);assert.match(html,/trottl-special-service\.js\?v=14/);assert.match(html,/trottl-special-ui\.js\?v=18/);assert.match(html,/trottl-special\.css\?v=23/);assert.match(html,/trottl-special-stop-fish\.js\?v=1/);assert.match(service,/get_trottl_special_fish_memory_view/);assert.match(service,/guessFishMemory: async/);assert.match(service,/syncFishMemory: async/);assert.match(ui,/fishMemory\?\.update\(snapshot\)/);});
test("dedicated SQL fixture checks pattern, timing and the five-way pool transactionally",()=>{const fixture=read("tests/fixtures/trottl-special-fish-memory.sql");assert.match(fixture,/deterministic 12-entry pattern/);assert.match(fixture,/exact current 20-percent production pool/i);assert.ok(fixture.startsWith("begin;\n"));assert.ok(fixture.endsWith("rollback;\n"));});
test("migration is additive, transactional and leaves Classic, PANIK, life and finale untouched",()=>{assert.ok(migration.startsWith("begin;\n"));assert.ok(migration.endsWith("commit;\n"));assert.equal((migration.match(/\$\$/g)??[]).length%2,0);assert.doesNotMatch(migration,/trottl_classic|special_apply_life|panic|finale/i);});
