"use strict";
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const root = path.join(__dirname, "..");
const read = file => fs.readFileSync(path.join(root, file), "utf8");
const sql = read("supabase/migrations/20260915000000_polish_trottl_special_rescue_and_result_flow.sql");
const ui = read("trottl-special-ui.js");
const css = read("trottl-special.css");
const classic = read("trottl-classic-ui.js");
const html = read("index.html");

assert.match(sql, /coalesce\(\(g->>'rescue'\)::boolean,false\)[\s\S]*\(g->>'result'\)::integer=6/);
assert.match(sql, /special_restore_life_locked\(p_session_id,actor_id\)[\s\S]*special_advance_locked/);
assert.doesNotMatch(sql.match(/if p_action='resolve'[\s\S]*?end if;/)?.[0] ?? "", /awaiting_roll|roulette/);
assert.match(sql, /interval '700 milliseconds'/);
assert.match(sql, /all_results_ready/);
assert.match(sql, /result_seen/);
assert.match(sql, /lifecycle_status in \('alive','critical'\)/);
assert.match(ui, /Ergebnisse von „\$\{m\.title \?\? m\.minigame_type\}“ Game/);
assert.doesNotMatch(ui, /Ergebnis bestätigen, um fortzufahren/);
assert.match(ui, /trottl-special-result-ready/);
assert.match(ui, /r\.reward === "transfer" \? "3er Trottl"/);
assert.match(ui, /r\.reward === "transfer" \? "weitergeben"/);
assert.match(ui, /`TROTTL \$\{g\.points\}\/3`/);
assert.match(classic, /trottlBadge\.textContent = "TROTTL"/);
assert.doesNotMatch(classic, /trottlBadge\.textContent = "3ER"/);
assert.match(css, /drop-shadow\(0 0 4px rgb\(255 255 255 \/ 72%\)\)/);
assert.match(css, /\.trottl-special-heart\.is-live \{ color: #ef4b65; filter: none; \}/);
assert.match(css, /\.trottl-special-result-ready/);
assert.match(css, /trottl-special-critical-badge \{[^}]*top: -8px/);
assert.match(html, /trottl-special\.css\?v=27/);
assert.match(html, /trottl-special-ui\.js\?v=20/);
assert.match(html, /trottl-classic-ui\.js\?v=44/);
console.log("trottl special final polish structure passed");
